language: go

go:
  - "1.11.x"

services:
  - mysql

addons:
  chrome: stable

install:
  - env GO111MODULE=on go get ./cmd/...  # install the goradd tool
  - cd ${TRAVIS_HOME}
  - cp -r ${TRAVIS_BUILD_DIR}/internal/install/goradd-project .
  - cp -r ${TRAVIS_BUILD_DIR}/internal/install/goradd-tmp .
  - cp -r ${TRAVIS_BUILD_DIR}/test/goradd-test .
  - echo "replace github.com/goradd/goradd => ${TRAVIS_BUILD_DIR}" >> ${TRAVIS_HOME}/goradd-project/go.mod
  - echo "replace github.com/goradd/goradd => ${TRAVIS_BUILD_DIR}" >> ${TRAVIS_HOME}/goradd-test/go.mod
  - env GO111MODULE=on goradd install -s2  # use the goradd tool to complete the install

before_script:
  - google-chrome-stable http://localhost:8000?all=1 &
  - mysql -e 'create database goradd;'; mysql -u root goradd < ${TRAVIS_BUILD_DIR}/examples/db/mysql.sql
#  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('12345') where User='root'; FLUSH PRIVILEGES;"

script:
  - cd ${TRAVIS_HOME}/goradd-test/codegen && env GO111MODULE=on go generate build.go  # Codegen
  - cd ${TRAVIS_HOME}/goradd-project && env GO111MODULE=on go test github.com/goradd/goradd/pkg/...  # Pkg unit tests
  - cd ${TRAVIS_HOME}/goradd-project && env GO111MODULE=on go test github.com/goradd/goradd/test/dbtest  # Db unit tests
  - cd ${TRAVIS_HOME}/goradd-test && env GO111MODULE=on ${TRAVIS_BUILD_DIR}/test/ci/test.sh  # Browser based tests
