language: go

go:
  - "1.11.x"

services:
  - mysql

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000?all=1 &

install:
  - env GO111MODULE=on go get -t -v ./...  # install the goradd tool
  - cd ${TRAVIS_HOME}
  - goradd install # Use the goradd tool to install dependencies
  - echo "replace github.com/goradd/goradd => ${TRAVIS_BUILD_DIR}" >> ${TRAVIS_HOME}/goradd-project/go.mod
  - cp ${TRAVIS_BUILD_DIR}/test/goradd-test ${TRAVIS_HOME}
  - echo "replace github.com/goradd/goradd => ${TRAVIS_BUILD_DIR}" >> ${TRAVIS_HOME}/goradd-test/go.mod

before_script:
  - mysql -e 'create database goradd;'; mysql -u root goradd < test/dbtest/mysql.sql
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('12345') where User='root'; FLUSH PRIVILEGES;"

script:
  - pushd ${TRAVIS_HOME}/goradd-test/codegen && env GO111MODULE=on go generate build.go ; popd  # Codegen
  - pushd ${TRAVIS_HOME}/goradd-project && env GO111MODULE=on go test github.com/goradd/goradd/pkg/... ; popd  # Pkg unit tests
  - pushd ${TRAVIS_HOME}/goradd-project && env GO111MODULE=on go test github.com/goradd/goradd/test/dbtest ; popd  # Db unit tests
  - pushd ${TRAVIS_HOME}/goradd-test && env GO111MODULE=on go run main.go ; popd  # Browser based tests
